---
- name: Create a website at AWS
  hosts: all
  become: true

  collections:
    - ansible.builtin
    - community.docker

  vars_files:
    - vars/vars.yml
  
  tasks:
    - name: Config server
      include_tasks: config-server.yml

    - name: Create docker-compose.yml file to deploy the website
      template:
        src: "docker-compose.yml.j2"
        dest: "/tmp/docker-compose.yml"

    - name: Generate the website index file
      template:
        src: "index.html.j2"
        dest: "/tmp/index.html"

    - name: Create and start the website (nginx) service
      docker_compose:
        project_src: /tmp
        restarted: true
      register: output

    - name: Show results
      debug:
        var: output

    - name: Copy a file into the container
      docker_container_copy_into:
        container: "{{ website_container_name }}"
        path: /tmp/index.html
        container_path: /usr/share/nginx/html/index.html

    - name: Remove temporary files
      file:
        state: absent
        path: "{{ item }}"
      loop:
        - "/tmp/docker-compose.yml"
        - "/tmp/index.html"
