name: Terraform

on:
  push:
    branches: [ "pipeline-cicd" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: ./lab-terraform-ansible/terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup SSH 
      shell: bash
      run: |
        pwd
        ls -la
        touch /tmp/sshkey.pub
        echo -e "${{secrets.ANSIBLE_SSH_PUB}}" > /tmp/sshkey.pub
        cat /tmp/sshkey.pub
      # run: |
      #   eval `ssh-agent -s`
      #   mkdir -p /home/runner/.ssh/
      #   touch /home/runner/.ssh/id_rsa
      #   echo -e "${{secrets.SSH_KEY}}" > /home/runner/.ssh/id_rsa
      #   chmod 700 /home/runner/.ssh/id_rsa
      #   ssh-keyscan -t rsa,dsa,ecdsa,ed25519 ${{secrets.SSH_HOST}} >> /home/runner/.ssh/known_hosts

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 

    - name: Terraform Plan
      run: terraform plan -input=false
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 

    - name: Terraform Apply
      # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 
